# Generated by Django 2.2.4 on 2019-10-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SofterPawInsights', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keys', models.CharField(blank=True, max_length=200, null=True)),
                ('clicks', models.CharField(blank=True, max_length=200, null=True)),
                ('impressions', models.CharField(blank=True, max_length=200, null=True)),
                ('ctr', models.CharField(blank=True, max_length=200, null=True)),
                ('position', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'performance',
                'managed': True,
            },
        ),
    ]
